# For more information: https://laravel.com/docs/sail
version: '3'
services:
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: 'wordpress'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: 'wordpress'
            MYSQL_USER: 'wordpress'
            MYSQL_PASSWORD: 'wordpress'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'sailmysql:/var/lib/mysql'
        networks:
            - sail
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p wordpress"]
            retries: 3
            timeout: 5s
networks:
    sail:
        driver: bridge
volumes:
    sailmysql:
        driver: local
